name: 'Netlify CLI'
description: 'Wraps the Netlify CLI'
author: 'Flexbase Technologies <https://github.com/flexbase-eng>'
branding:
  color: '#FF5745'
  icon: upload-cloud
inputs:
  args:
    description: 'Any command from https://cli.netlify.com/commands'
    required: true
runs:
  using: composite
  steps:
    - id: cli
      run: $GITHUB_ACTION_PATH/action.sh ${{ inputs.args }} --json
      shell: bash
outputs:
  netlify_output:
    description: 'Netlify output'
    value: ${{ steps.cli.outputs.NETLIFY_OUTPUT }}
  netlify_json:
    description: 'Netlify json output'
    value: ${{ fromJson(steps.cli.outputs.NETLIFY_OUTPUT) }}
