name: 'Netlify CLI'
description: 'Wraps the Netlify CLI'
author: 'Flexbase Technologies <https://github.com/flexbase-eng>'
branding:
  color: '#FF5745'
  icon: upload-cloud
inputs:
  args:
    description: 'Any command from https://cli.netlify.com/commands'
    required: true
runs:
  using: composite
  steps:
    - id: cli
      run: $GITHUB_ACTION_PATH/action.sh ${{ inputs.args }} --json
      shell: bash
    - name: cli_output_debug
      env:
        test_output: ${{ steps.cli.outputs.netlify_output }}
      run: |
        echo "$test_output"
        echo "${{ steps.cli.outputs.netlify_output }}"
      shell: bash
outputs:
  netlify_output:
    description: 'Netlify json output'
    value: ${{ steps.cli.outputs.netlify_output }}
