name: 'Create env file'
description: 'Creates an env file from given inputs'
author: 'Flexbase Technologies <https://github.com/flexbase-eng>'
branding:
  color: '#FF5745'
  icon: upload-cloud
inputs:
  file_name:
    description: 'The name of the file to be generated'
    required: true
    type: string
    default: '.env'
  file_path:
    description: 'The path of the file to be generated'
    required: true
    type: string
    default: 'dist'
  file_data:
    description: 'The data to write to the file'
    required: true
    type: string
  file_format:
    description: 'The format of the data'
    required: true
    type: choice
    default: 'dotenv'
    options:
      - dotenv
      - json

runs:
  using: 'node16'
  main: 'action.js'
