name: "OpenVPN-Connect"
description: "connect to OpenVPN server"
branding:
  icon: "lock"
  color: "green"
inputs:
  config:
    description: "OpenVPN profile file (.ovpn or .conf)."
    required: true
  autoload-config:
    description: "VPN Autoload Config is the username and password file (.autoload) to support auth-user-pass"
    required: false
runs:
  using: "node20"
  main: "src/index.js"
  post: "src/index.js"