name: "OpenVPN-Connect"
description: "Connect to an OpenVPN server"
branding:
  icon: "lock"
  color: "green"
inputs:
  config:
    description: "OpenVPN profile file (.ovpn or .conf)."
    required: true
runs:
  using: "node20"
  pre: "src/pre.js"
  main: "src/main.js"
  post: "src/post.js"